-- This is an empty migration.
-- ACTIVAR SEGURIDAD (RLS) PARA QUITAR ALERTAS --
ALTER TABLE "usuarios" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "roles" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "rol_modulo_permisos" ENABLE ROW LEVEL SECURITY;